# Generated by Django 5.2.8 on 2025-11-27 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_size', models.CharField(choices=[('1R', '1R'), ('1K', '1K'), ('1DK', '1DK'), ('1LDK', '1LDK'), ('2DK', '2DK'), ('2LDK', '2LDK'), ('3LDK', '3LDK'), ('house', 'House')], max_length=20)),
                ('trash_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('truck_type', models.CharField(choices=[('light', 'Light Truck'), ('1t', '1t Truck'), ('2t', '2t Truck'), ('2t_full', '2t Full Load'), ('2_trucks', '2 Trucks')], max_length=20)),
                ('booking_date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('has_elevator', models.BooleanField(default=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(max_length=254)),
                ('notes', models.TextField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='booking_images/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Bookings.booking')),
            ],
        ),
    ]
