# Generated by Django 5.2.8 on 2025-11-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingimage',
            name='image',
        ),
        migrations.AddField(
            model_name='bookingimage',
            name='image_url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
