# Generated by Django 5.2.8 on 2025-12-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_intent_id',
            field=models.CharField(blank=True, help_text='Strike PaymentIntent ID for family payment', max_length=255, null=True),
        ),
    ]
