# Generated by Django 5.2.8 on 2025-12-02 07:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_add_payment_intent_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Thời điểm đơn hàng được giao', null=True),
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('under_review', 'Đang xem xét'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('shipping', 'Đang gửi hàng'), ('received', 'Đã nhận hàng'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('return_type', models.CharField(choices=[('full', 'Hoàn trả toàn bộ'), ('partial', 'Hoàn trả một phần'), ('exchange', 'Đổi hàng')], default='full', max_length=20)),
                ('reason', models.CharField(max_length=100)),
                ('reason_detail', models.TextField(blank=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('fault_type', models.CharField(choices=[('shop_fault', 'Lỗi từ shop'), ('customer_fault', 'Lỗi từ khách hàng'), ('no_fault', 'Không có lỗi (đổi ý)'), ('pending_review', 'Chờ xác nhận')], default='pending_review', help_text='Xác nhận nguyên nhân hư hỏng: do shop, do khách, hay không có lỗi', max_length=20)),
                ('fault_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('fault_notes', models.TextField(blank=True, help_text='Ghi chú của admin về nguyên nhân')),
                ('days_since_delivery', models.IntegerField(default=0, help_text='Số ngày từ khi nhận hàng')),
                ('baseline_refund_amount', models.DecimalField(decimal_places=2, default=0, help_text='Số tiền hoàn trả dự kiến theo chính sách condition (baseline)', max_digits=10)),
                ('baseline_refund_percent', models.DecimalField(decimal_places=2, default=0, help_text='Phần trăm hoàn trả theo condition (100% hoặc 80%)', max_digits=5)),
                ('final_refund_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Số tiền hoàn trả cuối cùng sau khi xác nhận nguyên nhân', max_digits=10, null=True)),
                ('final_refund_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Phần trăm hoàn trả cuối cùng', max_digits=5, null=True)),
                ('return_shipping_label', models.CharField(blank=True, max_length=255)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('fault_confirmed_by', models.ForeignKey(blank=True, help_text='Admin xác nhận nguyên nhân', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_returns', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='Orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Return Request',
                'verbose_name_plural': 'Return Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('condition_at_return', models.CharField(blank=True, help_text='Tình trạng sản phẩm khi nhận lại', max_length=20)),
                ('original_condition', models.CharField(help_text='Tình trạng ban đầu', max_length=20)),
                ('days_since_delivery', models.IntegerField()),
                ('baseline_refund_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('baseline_refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_refund_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('received', 'Đã nhận hàng'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='Orders.orderitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Orders.returnrequest')),
            ],
            options={
                'verbose_name': 'Return Item',
                'verbose_name_plural': 'Return Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
