# Generated by Django 5.2.8 on 2025-12-02 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_order_delivered_at_returnrequest_returnitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnitem',
            name='condition_at_return',
            field=models.CharField(blank=True, help_text='Product condition when received back', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='original_condition',
            field=models.CharField(help_text='Original condition', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('received', 'Received'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='baseline_refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Expected refund amount based on condition policy (baseline)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='baseline_refund_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Refund percentage based on condition (100% or 80%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='days_since_delivery',
            field=models.IntegerField(default=0, help_text='Days since delivery'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='fault_confirmed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who confirmed the fault', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='fault_notes',
            field=models.TextField(blank=True, help_text='Admin notes about the fault'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='fault_type',
            field=models.CharField(choices=[('shop_fault', 'Shop Fault'), ('customer_fault', 'Customer Fault'), ('no_fault', 'No Fault (Change of Mind)'), ('pending_review', 'Pending Review')], default='pending_review', help_text='Confirm fault cause: shop fault, customer fault, or no fault', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='final_refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final refund amount after confirming fault cause', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='final_refund_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final refund percentage', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='return_type',
            field=models.CharField(choices=[('full', 'Full Return'), ('partial', 'Partial Return'), ('exchange', 'Exchange')], default='full', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('shipping', 'Shipping'), ('received', 'Received'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
