# Generated by Django 5.2.8 on 2025-12-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_alter_returnitem_condition_at_return_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, help_text='Payment deadline for FamilyMart payment (2 days after creation)', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Time when order was delivered to customer', null=True),
        ),
    ]
