# Generated by Django 5.2.8 on 2025-11-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition_detail',
            field=models.TextField(blank=True, help_text='Detailed description of condition (e.g. scratches, battery health)'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='JSON data for specs (e.g. screen_size, ram, etc.)'),
        ),
    ]
