# Generated by Django 5.2.8 on 2025-11-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_productcomment_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
