# Generated by Django 5.2.8 on 2025-11-26 05:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_product_sold_quantity_product_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Sale % for all products in this category', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Sale % for this specific product (Overrides category sale)', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
