# Generated by Django 5.2.8 on 2025-11-28 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_commentimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessory_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_for', to='Products.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='Products.product')),
            ],
            options={
                'verbose_name_plural': 'Accessories',
                'indexes': [models.Index(fields=['product'], name='Products_ac_product_e7c70b_idx')],
                'unique_together': {('product', 'accessory_product')},
            },
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to='Products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', '-viewed_at'], name='Products_us_user_id_926e5c_idx'), models.Index(fields=['product', '-viewed_at'], name='Products_us_product_ff6f4b_idx')],
            },
        ),
    ]
