# Generated by Django 5.2.8 on 2025-11-28 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_alter_userhistory_viewed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGeminiAnswer',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gemini_answer', serialize=False, to='Products.product')),
                ('answer', models.TextField(help_text='Câu trả lời từ Gemini AI')),
                ('question', models.TextField(help_text='Câu hỏi đã được gửi đến Gemini')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Gemini Answer',
                'verbose_name_plural': 'Product Gemini Answers',
                'ordering': ['-created_at'],
            },
        ),
    ]
