# Generated by Django 5.2.8 on 2025-12-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_productgeminianswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Đánh dấu sản phẩm đã được kiểm tra và đảm bảo chất lượng'),
        ),
    ]
