# Generated by Django 5.2.8 on 2025-12-02 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_product_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên chương trình giảm giá', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Mô tả chi tiết')),
                ('discount_type', models.CharField(choices=[('percent', 'Phần trăm (%)'), ('amount', 'Số tiền cố định (¥)')], default='percent', help_text='Loại giảm giá: phần trăm hoặc số tiền cố định', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Giá trị giảm (phần trăm hoặc số tiền)', max_digits=10)),
                ('start_date', models.DateTimeField(help_text='Ngày bắt đầu')),
                ('end_date', models.DateTimeField(blank=True, help_text='Ngày kết thúc (null = không giới hạn)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Kích hoạt/không kích hoạt')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Độ ưu tiên (số càng cao càng ưu tiên)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, help_text='Áp dụng cho các danh mục', related_name='discounts', to='Products.category')),
                ('parent_category', models.ForeignKey(blank=True, help_text='Áp dụng cho tất cả sản phẩm trong parent category và các sub-categories', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_discounts', to='Products.category')),
                ('products', models.ManyToManyField(blank=True, help_text='Áp dụng cho các sản phẩm cụ thể', related_name='discounts', to='Products.product')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'start_date', 'end_date'], name='Products_di_is_acti_00ae66_idx'), models.Index(fields=['is_active', 'priority'], name='Products_di_is_acti_c68595_idx')],
            },
        ),
    ]
