# Generated by Django 5.2.8 on 2025-12-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentimage',
            name='is_video',
            field=models.BooleanField(default=False, help_text='True if this is a video file'),
        ),
    ]
