# Generated by Django 5.2.8 on 2025-12-05 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_commentimage_is_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'verbose_name_plural': 'Accessories (Deprecated)'},
        ),
        migrations.CreateModel(
            name='CategoryAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessory_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_categories', to='Products.category')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_categories', to='Products.category')),
            ],
            options={
                'verbose_name_plural': 'Category Accessories',
                'indexes': [models.Index(fields=['category'], name='Products_ca_categor_6c1461_idx')],
                'unique_together': {('category', 'accessory_category')},
            },
        ),
    ]
