# Generated by Django 5.2.8 on 2025-12-09 06:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('description', models.TextField(verbose_name='説明')),
                ('condition', models.CharField(choices=[('new_unused', '新品・未使用'), ('like_new', '未使用に近い'), ('no_damage', '目立った傷や汚れなし'), ('minor_damage', 'やや傷や汚れあり'), ('has_damage', '傷や汚れあり')], default='like_new', max_length=20, verbose_name='状態')),
                ('location_prefecture', models.CharField(max_length=50, verbose_name='都道府県')),
                ('location_city', models.CharField(max_length=100, verbose_name='市区町村')),
                ('location_detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='詳細住所')),
                ('pickup_method', models.CharField(choices=[('direct', '直接引き取り（手渡し）'), ('consult', '要相談')], default='direct', max_length=20, verbose_name='受け取り方法')),
                ('status', models.CharField(choices=[('available', '募集中'), ('reserved', '予約済み'), ('completed', '終了'), ('cancelled', 'キャンセル')], default='available', max_length=20, verbose_name='状態')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='カテゴリ')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='閲覧数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FreeItemImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=500, verbose_name='画像URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='順序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('free_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='FreeItems.freeitem')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FreeItemMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('free_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='FreeItems.freeitem')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_free_item_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_free_item_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='freeitem',
            index=models.Index(fields=['status', '-created_at'], name='FreeItems_f_status_bc4ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='freeitem',
            index=models.Index(fields=['location_prefecture', 'location_city'], name='FreeItems_f_locatio_83441b_idx'),
        ),
        migrations.AddIndex(
            model_name='freeitem',
            index=models.Index(fields=['user'], name='FreeItems_f_user_id_82195e_idx'),
        ),
        migrations.AddIndex(
            model_name='freeitemmessage',
            index=models.Index(fields=['free_item', 'created_at'], name='FreeItems_f_free_it_039b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='freeitemmessage',
            index=models.Index(fields=['sender', 'receiver'], name='FreeItems_f_sender__8fc1db_idx'),
        ),
    ]
