# Generated by Django 5.2.8 on 2025-12-09 06:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeItems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freeitem',
            options={'ordering': ['-created_at'], 'verbose_name': '無料アイテム', 'verbose_name_plural': '無料アイテム'},
        ),
        migrations.AlterModelOptions(
            name='freeitemimage',
            options={'ordering': ['order', 'created_at'], 'verbose_name': '無料アイテム画像', 'verbose_name_plural': '無料アイテム画像'},
        ),
        migrations.AlterModelOptions(
            name='freeitemmessage',
            options={'ordering': ['created_at'], 'verbose_name': '無料アイテムメッセージ', 'verbose_name_plural': '無料アイテムメッセージ'},
        ),
        migrations.CreateModel(
            name='FreeItemView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='For anonymous users', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('free_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_views', to='FreeItems.freeitem')),
                ('user', models.ForeignKey(blank=True, help_text='Null for anonymous users', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_item_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '無料アイテム閲覧',
                'verbose_name_plural': '無料アイテム閲覧',
                'indexes': [models.Index(fields=['free_item', 'user'], name='FreeItems_f_free_it_3423fd_idx'), models.Index(fields=['free_item', 'ip_address'], name='FreeItems_f_free_it_53df14_idx')],
                'unique_together': {('free_item', 'user')},
            },
        ),
    ]
