# Generated by Django 5.2.8 on 2025-12-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeItems', '0002_alter_freeitem_options_alter_freeitemimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeitem',
            name='show_email',
            field=models.BooleanField(default=False, verbose_name='メール公開'),
        ),
    ]
