# Generated by Django 5.2.8 on 2025-11-24 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('visa', 'VISA'), ('mastercard', 'Mastercard'), ('jcb', 'JCB'), ('amex', 'American Express'), ('other', 'Other')], default='visa', max_length=20)),
                ('last4', models.CharField(max_length=4)),
                ('exp_month', models.PositiveSmallIntegerField()),
                ('exp_year', models.PositiveSmallIntegerField()),
                ('card_holder_name', models.CharField(max_length=255)),
                ('gateway', models.CharField(default='manual', max_length=50)),
                ('gateway_customer_id', models.CharField(blank=True, max_length=255)),
                ('gateway_payment_method_id', models.CharField(max_length=255)),
                ('fingerprint', models.CharField(blank=True, help_text='Dùng để phát hiện cùng một thẻ được thêm nhiều lần (từ gateway).', max_length=255)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'payment_methods',
                'indexes': [models.Index(fields=['user', 'is_active'], name='payment_met_user_id_a6fdd9_idx')],
            },
        ),
    ]
