# Generated by Django 5.2.8 on 2025-12-09 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='admin_reply',
            field=models.TextField(blank=True, help_text="Admin's reply to this inquiry", null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='replied_by',
            field=models.ForeignKey(blank=True, help_text='Admin who replied', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
