# Generated by Django 5.2.8 on 2025-12-10 05:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(max_length=20)),
                ('suggested_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pricing_reasoning', models.TextField()),
                ('hit_count', models.PositiveIntegerField(default=0, help_text='Number of times this cache was used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_used_at'],
                'indexes': [models.Index(fields=['cache_key'], name='AIPricing_p_cache_k_b3a10a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PricingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('condition', models.CharField(choices=[('new', 'Mới'), ('like_new', 'Như mới'), ('good', 'Tốt'), ('fair', 'Khá'), ('poor', 'Kém')], max_length=20)),
                ('image_urls', models.JSONField(default=list, help_text='List of image URLs')),
                ('image_hash', models.CharField(db_index=True, help_text='Hash of first image for caching', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Đang xử lý'), ('validated', 'Đã xác thực'), ('priced', 'Đã định giá'), ('error', 'Lỗi'), ('rejected', 'Từ chối')], default='pending', max_length=20)),
                ('validation_result', models.JSONField(blank=True, help_text='Gemini validation response', null=True)),
                ('pricing_result', models.JSONField(blank=True, help_text='Gemini pricing response', null=True)),
                ('suggested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='0-1 confidence score', null=True)),
                ('pricing_reasoning', models.TextField(blank=True, help_text='AI reasoning for the price')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['image_hash'], name='AIPricing_p_image_h_aa012c_idx'), models.Index(fields=['status'], name='AIPricing_p_status_66a22b_idx'), models.Index(fields=['user', '-created_at'], name='AIPricing_p_user_id_ea1a6f_idx')],
            },
        ),
    ]
