# Generated by Django 5.2.8 on 2025-12-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIPricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrequest',
            name='title',
            field=models.CharField(default='', help_text='Tên sản phẩm', max_length=255),
        ),
    ]
